name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Python
        shell: powershell
        run: |
          python --version
          where.exe python
          pip --version

      - name: Install dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SCA tool - pip-audit
        shell: powershell
        run: |
          python -m pip install pip-audit

      - name: Run SCA - pip-audit
        shell: powershell
        run: |
          pip-audit -r requirements.txt --format json --output pip-audit-report.json
          pip-audit -r requirements.txt
          
      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pip-audit-sca-report
          path: pip-audit-report.json
          
      - name: Run SonarQube scan
        shell: powershell
        run: |
          & "C:\sonar-scanner\bin\sonar-scanner.bat" `
            -D"sonar.projectKey=wilmarguarin_Implementacion_DevSecOps_a958c060-abcc-49f0-9d6c-fc1f9853db09" `
            -D"sonar.projectName=Implementacion_DevSecOps" `
            -D"sonar.sources=." `
            -D"sonar.sourceEncoding=UTF-8" `
            -D"sonar.python.version=3.11" `
            -D"sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/node_modules/**,**/static/**" `
            -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}" `
            -D"sonar.token=${{ secrets.SONAR_TOKEN }}"