name: SonarQube Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Python
        shell: powershell
        run: |
          python --version
          where.exe python
          pip --version

      - name: Install dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          - name: Run SonarQube scan
        shell: powershell
        run: |
          & "C:\sonar-scanner\bin\sonar-scanner.bat" `
            "-Dsonar.projectKey=wilmarguarin_Implementacion_DevSecOps_a958c060-abcc-49f0-9d6c-fc1f9853db09" `
            "-Dsonar.projectName=Implementacion_DevSecOps" `
            "-Dsonar.sources=." `
            "-Dsonar.sourceEncoding=UTF-8" `
            "-Dsonar.python.version=3.11" `
            "-Dsonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/node_modules/**,**/static/**" `
            "-Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}" `
            "-Dsonar.token=${{ secrets.SONAR_TOKEN }}"